---
- name: "Directory Exists | {{ item }}"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ robot_sweatshop_user }}"
    group: "{{ robot_sweatshop_group }}"
    mode: 0775
  with_items:
    - "{{ robot_sweatshop_runtime_root }}"
    - "{{ robot_sweatshop_log_root }}"
    - "{{ robot_sweatshop_config_root }}"
    - "{{ robot_sweatshop_config_root }}/jobs"
    - "{{ robot_sweatshop_db_root }}"
  tags:
    - directory-structure
    - robot_sweatshop

- name: Generate config file | robot_sweatshop
  command: "{{ item }}"
  with_items:
    - /usr/local/bin/sweatshop config --auto
    - "cp .robot_sweatshop/config.yaml {{ robot_sweatshop_config_root }}"

- name: Configure | robot_sweatshop
  lineinfile:
    state: present
    dest: "{{ robot_sweatshop_config_root }}/config.yaml"
    regexp: "{{ item.key }}:"
    line: "{{ item.key }}: {{ item.value }}"
  with_items:
    - { key: pidfile_path,        value: "{{ robot_sweatshop_runtime_root }}" }
    - { key: logfile_path,        value: "{{ robot_sweatshop_log_root }}" }
    - { key: job_path,            value: "{{ robot_sweatshop_config_root }}/jobs" }
    - { key: workspace_path,      value: "{{ robot_sweatshop_config_root }}/workspaces" }
    - { key: database_path,       value: "{{ robot_sweatshop_db_root }}" }
    - { key: scripts_path,        value: "{{ robot_sweatshop_config_root }}/scripts" }
    - { key: http_bind,           value: "{{ robot_sweatshop_http_bind }}" }
    - { key: http_cross_origin,   value: "{{ robot_sweatshop_http_cross_origin }}" }
    - { key: overseer_port,       value: "{{ robot_sweatshop_overseer_port }}" }
    - { key: api_port,            value: "{{ robot_sweatshop_api_port }}" }
    - { key: conveyor_port,       value: "{{ robot_sweatshop_conveyor_port }}" }
    - { key: payload_parser_port, value: "{{ robot_sweatshop_payload_parser_port }}" }
    - { key: job_dictionary_port, value: "{{ robot_sweatshop_job_dictionary_port }}" }
    - { key: worker_port,         value: "{{ robot_sweatshop_worker_port }}" }
    - { key: api_url,             value: "application.{{ project }}-{{ environment_tier }}.{{ domain }}:{{ robot_sweatshop_api_port }}" }
    - { key: job_timeout_length,  value: "{{ robot_sweatshop_job_timeout }}" }
  notify: Reload Service | robot_sweatshop

- name: "Upload Config | robot_sweatshop | {{ item.name }} job"
  template:
    src: etc/robot_sweatshop/jobs/job.yaml
    dest: "{{ robot_sweatshop_config_root }}/jobs/{{ item.name }}.yaml"
    owner: "{{ robot_sweatshop_user }}"
    group: nogroup
    mode: 0644
  with_items: robot_sweatshop_jobs
  when: robot_sweatshop_jobs
  notify: Reload Service | robot_sweatshop
  tags:
    - robot_sweatshop
    - job-configuration
